### ISSUE TITLE
make this OS path safe

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/pyhat_qgis#1]
https://github.com/USGS-Astrogeology/pyhat_qgis/blob/6b37502cc4268e02ac949a5f0cd8d69afb99b19a/pyhat.py#L287

This section is not OS path safe. I would try to use os.path.basename. This seemed to worked for QGIS in Windows. I tried without setting a path in the QGIS dialog or setting "C:\Temp\" but any path should work.

```
        base=os.path.basename(layer_path)
        new_filename = (str(func) + '_' + base + '.tif')

        # Creates the new filepath for the image
        new_filepath = os.path.join(str(PyhatDialog.img_outpath), new_filename)
```

I didn't look over the code for other potential path issues.

**Comment by tgiroux** [comment]
I made this change and it ran smoothly. Didn't look into other potential path issues, not really familiar with what might cause these problems. I figure that could be something for Thatcher to take a look at.

**Comment by thareUSGS** [comment]
+1. Looks all good to me. I did a quick glance over some of the code and I didn't see any other path issues, We just need to watch out for Implied "*nix" paths like "/home/...". Using python os.path routines helps to be OS agnostic.

**Comment by thareUSGS** [comment]
@tgiroux Oops I assumed your fix was in. Feel free to issue a pull request into Astro from your repo

**Comment by thareUSGS** [comment]
fixed in https://github.com/USGS-Astrogeology/pyhat_qgis/pull/4
