### ISSUE TITLE
PyHat menu pulldown not removed

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/pyhat_qgis#2]
When I turn on/off PyHat as an extension, the PyHat pulldown isn't removed. I end up with several PyHat pulldowns in the menu bar. 

It is also creating an unnecessary and empty toolbar. Can that be turned off?

**Comment by tgiroux** [comment]
I made some changes on my dev branch that stop the empty toolbar from generating.

Still working on finding the problem with the PyHat pulldown. I think the `unload` function in pyhat_qgis/pyhat.py should remove the pulldown correctly, so I suspect that it isn't being called for some reason.

I'm also seeing two PyHat pulldowns generate upon initial plugin installation. Not sure if it's a problem with my environment, can anyone verify?

**Comment by thareUSGS** [comment]
I am not seeing two generated. Before closing QGIS uncheck the PyHat plug-in. Upon restarting I am not getting an a PyHat menu item (good). Turning it on once it seems to be working. Thus I think your unload should fix my issue at least.

**Comment by thareUSGS** [comment]
looks fixed in https://github.com/USGS-Astrogeology/pyhat_qgis/pull/4
