### ISSUE TITLE
Don't select newly added image (if possible)

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/pyhat_qgis#3]
This may not be an option to disable. When I select the main image (e.g. M3 cube) and run an algo, the new image that is loaded is selected. This makes running many algos a tiny bit more of  a pain. Can the selected (M3) selection be maintained over many algo runs...? Meaning to not select the newly added image.

**Comment by tgiroux** [comment]
There doesn't appear to be straightforward way to implement this.
I agree that it's an annoyance and may cause some confusion, so I added a line at the bottom of the install guide pointing it out

**Comment by tthatcher95** [comment]
@thareUSGS I messaged @tgiroux about how to fix this. PR#4 should be updated with this soon, and then we can close the issues.
