### ISSUE TITLE
reminder: projection testing for plug-in, CRISM

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/pyhat_qgis#6]
https://github.com/USGS-Astrogeology/pyhat_qgis/blob/6cd25b980740087e08a3ae4abbfd7404f1c48777/pyhat.py#L291

While this should work, this line would cause a failed output (even within the try/except). 
`            array_to_raster(modified_img, new_filepath, bittype='GDT_Float32', projection=img.spatial_reference)`

my current work-around was to simply remove projection=... This is not ideal since the output will not have a defined projection.
`            array_to_raster(modified_img, new_filepath, bittype='GDT_Float32')`

It should be quickly testable using any PyHAT algo for a CRISM image which most are map projected (e.g. frt000047a3_07_if166j_mtr3.img ),

 I haven't really figured out the issue but GDAL is not finding an sqlite database which houses the projections. This might be a QGIS conda issue.

**Comment by jlaura** [comment]
@thareUSGS Can you please post the stack trace?

**Comment by thareUSGS** [comment]
oof - I am still getting the proj.db error. I double check that the new line to enable  gdal.UseExceptions() was there too.

I guess the recommendation is to still diable writing the projection for now. I guess it could be a user setting in the GUI. e.g. a check box in the pull-down? By default it is off, but let the user try to turn it on...?

[ ] try to write projection to output


here is the stack trace
```
An error has occurred while executing Python code: 

RuntimeError 
Traceback (most recent call last):
  File "C:/Users/trent/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyhat_qgis-master\pyhat.py", line 293, in run_algorithm
    array_to_raster(modified_img, new_filepath, bittype='GDT_Float32',
  File "D:\Apps\Anaconda3\envs\qgis_pyhat\lib\site-packages\plio\io\io_gdal.py", line 608, in array_to_raster
    dataset.FlushCache()
  File "D:\Apps\Anaconda3\envs\qgis_pyhat\lib\site-packages\osgeo\gdal.py", line 2144, in FlushCache
    return _gdal.Dataset_FlushCache(self, *args)
RuntimeError: PROJ: proj_create_from_name: Cannot find proj.db

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/trent/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyhat_qgis-master\pyhat.py", line 297, in run_algorithm
    array_to_raster(modified_img, new_filepath, bittype='GDT_Float32')
  File "D:\Apps\Anaconda3\envs\qgis_pyhat\lib\site-packages\plio\io\io_gdal.py", line 592, in array_to_raster
    dataset = driver.Create(file_name, x, y, bands, getattr(gdal, bittype))
  File "D:\Apps\Anaconda3\envs\qgis_pyhat\lib\site-packages\osgeo\gdal.py", line 1774, in Create
    return _gdal.Driver_Create(self, *args, **kwargs)
RuntimeError


Python version: 3.8.2 | packaged by conda-forge | (default, Apr 24 2020, 07:34:03) [MSC v.1916 64 bit (AMD64)] 
QGIS version: 3.12.2-București București, exported 

Python Path:
D:/Apps/Anaconda3/envs/qgis_pyhat/Library/./python
C:/Users/trent/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/trent/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
D:/Apps/Anaconda3/envs/qgis_pyhat/Library/./python/plugins
D:\Apps\Anaconda3\envs\qgis_pyhat\Library\python
D:\Apps\Anaconda3\envs\qgis_pyhat\Library\python\plugins
C:\Users\trent
D:\Apps\Anaconda3\envs\qgis_pyhat\python38.zip
D:\Apps\Anaconda3\envs\qgis_pyhat\DLLs
D:\Apps\Anaconda3\envs\qgis_pyhat\lib
D:\Apps\Anaconda3\envs\qgis_pyhat\Library\bin
D:\Apps\Anaconda3\envs\qgis_pyhat
D:\Apps\Anaconda3\envs\qgis_pyhat\lib\site-packages
C:/Users/trent/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\trent\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\GeodesicDensifier
.
```

**Comment by AustinSanders** [comment]
@thareUSGS That's interesting -- I can't reproduce the error.  What steps should I take in order to reproduce?

I'm currently using:
 add layer -> add raster layer -> selecting a crism .img file
then
 PyHAT -> crism -> bd1300

and it works out of the box.

**Comment by jlaura** [comment]
@thareUSGS That's a proj4 error. What version of proj do you have installed? I would bet you have an old version where this was an issue. The newer packaging seems to have fixed the issue.

**Comment by jlaura** [comment]
Here is an issue on Proj. I think you are seeing GDAL wrap the error.

https://github.com/conda-forge/pyproj-feedstock/issues/29

**Comment by thareUSGS** [comment]
I used the installation from about one month ago - I can try it again though. https://github.com/USGS-Astrogeology/PyHAT/wiki/Use-PyHAT-in-prototype-QGIS-Plugin

here is my environment:
[environment.yml.txt](https://github.com/USGS-Astrogeology/pyhat_qgis/files/5075703/environment.yml.txt)

**Comment by thareUSGS** [comment]
Check-box for trying to write out the map projection was implemented as work-around for this issue under https://github.com/USGS-Astrogeology/pyhat_qgis/pull/8 . Thus I am closing will open a new ticket to address this "proj.db" issue under Windows Anaconda. Lots of testing to resolve environment variables was attempted under the standard CMD and Power Shells (to no avail). It is interesting to note that PROJ_LIB was defined under CMD but not under a PowerShell. But it still made no difference for being able to support writing out a projection. This is not true for QGIS built-in raster commands (e.g. raster calculator) which has no issues writing out a projection in a created file - very odd...?
